src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $nombre = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $apellidoPaterno = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $apellidoMaterno = null;

    #[ORM\Column(nullable: true)]
    private ?bool $activo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $ultimoAcceso = null;

    #[ORM\ManyToMany(targetEntity: Permiso::class, inversedBy: 'users')]
    private Collection $permisos;

    #[ORM\ManyToMany(targetEntity: Grupo::class, inversedBy: 'users')]
    private Collection $grupos;

    public function __construct()
    {
        $this->permisos = new ArrayCollection();
        $this->grupos = new ArrayCollection();
        $this->activo = true;
      //  $this->setUltimoAcceso(new \DateTime("now"));
    }

    public function getNombreCompleto()
    {
        return $this->nombre.' '.$this->apellidoPaterno.' '.$this->apellidoMaterno;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array {
        
        // guarantee every user at least has ROLE_USER
        $grupos = $this->grupos;
        
        foreach ($grupos as $grupo){
            
            $permisos = $grupo->getPermisos();
            foreach($permisos as $permiso) {
                
                $roles[] = $permiso->getRole();
                
            }
        }
        $permisos = $this->permisos;
        foreach($permisos as $permiso) {

                $roles[] = $permiso->getRole();
        }

        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }


    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password = null): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellidoPaterno(): ?string
    {
        return $this->apellidoPaterno;
    }

    public function setApellidoPaterno(?string $apellidoPaterno): self
    {
        $this->apellidoPaterno = $apellidoPaterno;

        return $this;
    }

    public function getApellidoMaterno(): ?string
    {
        return $this->apellidoMaterno;
    }

    public function setApellidoMaterno(?string $apellidoMaterno): self
    {
        $this->apellidoMaterno = $apellidoMaterno;

        return $this;
    }

    public function isActivo(): ?bool
    {
        return $this->activo;
    }

    public function setActivo(?bool $activo): self
    {
        $this->activo = $activo;

        return $this;
    }

    public function getUltimoAcceso(): ?\DateTimeInterface
    {
        return $this->ultimoAcceso;
    }

    public function setUltimoAcceso(?\DateTimeInterface $ultimoAcceso): self
    {
        $this->ultimoAcceso = $ultimoAcceso;

        return $this;
    }

    /**
     * @return Collection<int, Permiso>
     */
    public function getPermisos(): Collection
    {
        return $this->permisos;
    }

    public function addPermiso(Permiso $permiso): self
    {
        if (!$this->permisos->contains($permiso)) {
            $this->permisos->add($permiso);
        }

        return $this;
    }

    public function removePermiso(Permiso $permiso): self
    {
        $this->permisos->removeElement($permiso);

        return $this;
    }

    /**
     * @return Collection<int, Grupo>
     */
    public function getGrupos(): Collection
    {
        return $this->grupos;
    }

    public function addGrupo(Grupo $grupo): self
    {
        if (!$this->grupos->contains($grupo)) {
            $this->grupos->add($grupo);
        }

        return $this;
    }

    public function removeGrupo(Grupo $grupo): self
    {
        $this->grupos->removeElement($grupo);

        return $this;
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;


class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'required' => true,
                'attr' => ["autocomplete" => "off"]
            ])
            ->add('password', RepeatedType::class, array(
                'type' => PasswordType::class,
                'invalid_message' => 'Las contraseñas deben ser iguales.',
                
                'required' => $options['password_required'],
                'first_options'  => array('label' => 'Password'),
                'second_options' => array('label' => 'Repetir Password'),
                'attr' => array('autocomplete' => 'new-password', 'placeholder' => 'Contraseña'),
            ))
            ->add('nombre')
            ->add('apellidoPaterno')
            ->add('apellidoMaterno')
            ->add('activo')
        //    ->add('ultimoAcceso')
            ->add('permisos')
            ->add('grupos')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'password_required' => true,
        ]);
    }
}

src/Controller/Backend/DefaultController.php
<?php

namespace App\Controller\Backend;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class DefaultController extends AbstractController
{
    #[Route('/admin', name: 'app_default')]
    public function index(Request $request): Response
    {
       
        return $this->render('backend/default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
        
    }

    
}

src/Controller/Backend/GrupoController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Grupo;
use App\Form\GrupoType;
use App\Repository\GrupoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/grupo')]
class GrupoController extends AbstractController
{
    #[Route('/', name: 'app_grupo_index', methods: ['GET'])]
    public function index(GrupoRepository $grupoRepository): Response
    {
        return $this->render('backend/grupo/index.html.twig', [
            'grupos' => $grupoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_grupo_new', methods: ['GET', 'POST'])]
    public function new(Request $request, GrupoRepository $grupoRepository): Response
    {
        $grupo = new Grupo();
        $form = $this->createForm(GrupoType::class, $grupo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $grupoRepository->save($grupo, true);

            return $this->redirectToRoute('app_grupo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backend/grupo/new.html.twig', [
            'grupo' => $grupo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_grupo_show', methods: ['GET'])]
    public function show(Grupo $grupo): Response
    {
        return $this->render('backend/grupo/show.html.twig', [
            'grupo' => $grupo,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_grupo_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Grupo $grupo, GrupoRepository $grupoRepository): Response
    {
        $form = $this->createForm(GrupoType::class, $grupo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $grupoRepository->save($grupo, true);

            return $this->redirectToRoute('app_grupo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backend/grupo/edit.html.twig', [
            'grupo' => $grupo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_grupo_delete', methods: ['POST'])]
    public function delete(Request $request, Grupo $grupo, GrupoRepository $grupoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$grupo->getId(), $request->request->get('_token'))) {
            $grupoRepository->remove($grupo, true);
        }

        return $this->redirectToRoute('app_grupo_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Backend/PermisoController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Permiso;
use App\Form\PermisoType;
use App\Repository\PermisoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/permiso')]
class PermisoController extends AbstractController
{
    #[Route('/', name: 'app_permiso_index', methods: ['GET'])]
    public function index(PermisoRepository $permisoRepository): Response
    {
        return $this->render('backend/permiso/index.html.twig', [
            'permisos' => $permisoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_permiso_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PermisoRepository $permisoRepository): Response
    {
        $permiso = new Permiso();
        $form = $this->createForm(PermisoType::class, $permiso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $permisoRepository->save($permiso, true);

            return $this->redirectToRoute('app_permiso_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backend/permiso/new.html.twig', [
            'permiso' => $permiso,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_permiso_show', methods: ['GET'])]
    public function show(Permiso $permiso): Response
    {
        return $this->render('backend/permiso/show.html.twig', [
            'permiso' => $permiso,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_permiso_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Permiso $permiso, PermisoRepository $permisoRepository): Response
    {
        $form = $this->createForm(PermisoType::class, $permiso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $permisoRepository->save($permiso, true);

            return $this->redirectToRoute('app_permiso_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backend/permiso/edit.html.twig', [
            'permiso' => $permiso,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_permiso_delete', methods: ['POST'])]
    public function delete(Request $request, Permiso $permiso, PermisoRepository $permisoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$permiso->getId(), $request->request->get('_token'))) {
            $permisoRepository->remove($permiso, true);
        }

        return $this->redirectToRoute('app_permiso_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/backend/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i>&nbsp; Eliminar</button>
</form>

templates/backend/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="row">
        <div class=" col-lg-3 col-sm-3">
           <button class="btn btn-primary btn-sm" title="Guardar"><i class="fas fa-save"></i>&nbsp;{{ button_label|default('Guardar') }}</button>
        </div>
    </div>    
{{ form_end(form) }}

templates/backend/user/edit_modal.html.twig
<div id="modal-add-user" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Editar usuario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        {{ include('backend/user/_delete_form.html.twig') }}

                    </li>
                </ul>
                {{ include('backend/user/_form.html.twig', { 'button_label': ' Actualizar'}) }}
            </div>
            <div class="modal-footer">
            {#    <button type="button" class="btn btn-sm btn-warning" data-dismiss="modal"><i class="fas fa-times-circle"></i>&nbsp; Cancelar</button>
              #}
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#modal-add-user').modal('show');

    $("form").submit(function(){
        blockPage();
    });
</script>

templates/backend/user/index.html.twig
{% extends 'backend/layout.html.twig' %}

{% block title %}User index{% endblock %}
{% block page_title %}
<h4 class="m-0"><i class="fa fa-bars" aria-hidden="true"></i>&nbsp; Lista de usuarios</h4>
{% endblock %}
{% block page_description %}                        
    <li class="breadcrumb-item active"> Lista de usuarios</li>
{% endblock %}

{% block page_content %}

<div class="mb-2">
    <button type="button" id="" class="btn btn-primary btn-add-item" data-href="{{ path('app_user_new_modal') }}"><i class="fas fa-plus-circle" aria-hidden="true"></i> Nuevo</button>
</div>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id ="lista-User"class="table table-bordered nowrap table-hover table-striped w-100">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Email</th>
                            <th>Nombre</th>
                            <th>Activo</th>
                            <th>Ultimo Acceso</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.nombreCompleto }}</td>
                            <td>{{ user.activo ? 'Si' : 'No' }}</td>
                            <td>{{ user.ultimoAcceso ? user.ultimoAcceso|date('Y-m-d H:i:s') : '' }}</td>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a class="btn-show-item btn btn-info btn-sm" title="Consultar" data-href="{{ path('app_user_show', {'id': user.id}) }}"><i class="fas fa-search"></i></a>
                                    <a class="btn-edit-item btn btn-primary btn-sm" title="Editar" data-href="{{ path('app_user_edit_modal', {'id': user.id}) }}"><i class="fas fa-edit"></i></a>
                                </div>
                               
                            </td>
                        </tr>
                        {% else %}
                            <tr>
                                <td colspan="6">no records found</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div> <!-- /.col-md-12-->
    </div> <!-- /.row -->
<div id="contenedor-modales"></div>
{% endblock %}
    {% block javascripts_in_page %}
        <script type="text/javascript">
        $(document).ready(function () {
            
            $(".btn-add-item").click(function (e) {
                e.preventDefault();
                blockPage();
                url = $(this).attr('data-href');
                $.ajax({
                    url: url,
                    dataType: "JSON",
                    type: "GET",
                    data: {
                        //var1: valor,
                        //var2: "string"
                    },
                    success: function(data, textStatus, jqXHR){
                        if(data.code == 200) {
                            $('#contenedor-modales').html(data.html);
                            unblockPage();
                        } else {
                            //lanzar error
                        }
                    },
                    error: function(qXHR, textStatus, errorThrow) {
                        createNotification('error', 'Error al procesar la peticion...');
                        unblockPage();
                    }
                });
            }); //End agregar item

             $(".btn-edit-item").click(function(e){
            e.preventDefault();
            blockPage();
            url = $(this).attr('data-href');            
            $.ajax({
                url: url,
                dataType: "JSON",
                type: "GET",
                data: {
                    

                },
                success: function(data, textStatus, jqXHR){
                    if(data.code == 200) {
                        $('#contenedor-modales').html(data.html);
                        unblockPage();
                    } else {
                        //lanzar error
                    }
                },
                error: function(qXHR, textStatus, errorThrow) {
                    createNotification('error', 'Error al procesar la peticion...');
                    unblockPage();
                }
            });
        }); //End editar-item

        $(".btn-show-item").click(function(e){
            e.preventDefault();
            blockPage();
            url = $(this).attr('data-href');            
            $.ajax({
                url: url,
                dataType: "JSON",
                type: "GET",
                data: {
                    

                },
                success: function(data, textStatus, jqXHR){
                    if(data.code == 200) {
                        $('#contenedor-modales').html(data.html);
                        unblockPage();
                    } else {
                        //lanzar error
                    }
                },
                error: function(qXHR, textStatus, errorThrow) {
                    createNotification('error', 'Error al procesar la peticion...');
                    unblockPage();
                }
            });
        }); //End show-item



        });
    </script>

    {% endblock %}

templates/backend/user/new_modal.html.twig
<div id="modal-add-user" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Usuario nuevo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ include('backend/user/_form.html.twig') }}
            </div>
            <div class="modal-footer">
                {#  <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cancelar</button>  #}
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#modal-add-user').modal('show');

    $("form").submit(function(){
        blockPage();
    });
</script>

templates/backend/user/show.html.twig
<div id="modal-show-user" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Consulta Usuario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ user.nombre }}</td>
            </tr>
            <tr>
                <th>ApellidoPaterno</th>
                <td>{{ user.apellidoPaterno }}</td>
            </tr>
            <tr>
                <th>ApellidoMaterno</th>
                <td>{{ user.apellidoMaterno }}</td>
            </tr>
            <tr>
                <th>Activo</th>
                <td>{{ user.activo ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>UltimoAcceso</th>
                <td>{{ user.ultimoAcceso ? user.ultimoAcceso|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>
      </div>
      <div class="modal-footer">
        
        <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cancelar</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $('#modal-show-user').modal('show');
    $("form").submit(function(){
        blockPage();
    });
</script>